"""added email verification

Revision ID: 8b0b4b906da6
Revises: 7fba11e67546
Create Date: 2025-01-06 19:55:46.795735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b0b4b906da6'
down_revision: Union[str, None] = '7fba11e67546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('code_expiration', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'code_expiration')
    op.drop_column('users', 'last_code')
    # ### end Alembic commands ###
