services:
  db:
    image: postgres:16.4
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${POSTGRES_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
  api:
    build:
      dockerfile: api.dockerfile
    environment:
      MODULE_NAME: 'api'
      MAX_WORKERS: 10
    env_file:
      - .env
    ports:
      - 9000:80
    volumes:
      - ./assets:/app/assets
      - ./static:/app/static
    depends_on:
      - db
      - mongodb
  admin:
    build:
      dockerfile: admin.dockerfile
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
      - ./assets:/app/assets
    depends_on:
      - db
      - mongodb
